name: Luacheck
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  sile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Format
        uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.TOKEN }}
          version: latest
          args: --check .
      - name: Lint
        uses: lunarmodules/luacheck@v1
